import type { Metadata } from "next";
import { JetBrains_Mono, Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/navbar";
import 'highlight.js/styles/nord.css';


const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrains.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
